name: SAP BTP deployment with cTMS
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          cache: npm
      - run: npm i -g @sap/cds-dk mbt
      - run: npm i
      - run: npm run build
      - name: deploy-to-sap-btp-with-ctms
        uses: mauriciolauffer/deploy-to-sap-btp-with-ctms@v0.0.3
        with:
          CTMS_TOKEN_SERVICE_URL: ${{ vars.CTMS_TOKEN_SERVICE_URL }}
          CTMS_CLIENT_ID: ${{ secrets.CTMS_CLIENT_ID }}
          CTMS_CLIENT_SECRET: ${{ secrets.CTMS_CLIENT_SECRET }}
          CTMS_API_URL: ${{ vars.CTMS_API_URL }}
          CTMS_NODE_NAME: ${{ vars.CTMS_NODE_NAME }}
          CTMS_FILE_PATH: ${{ vars.CTMS_FILE_PATH }}
          CTMS_TR_DESCRIPTION: ${{ vars.CTMS_TR_DESCRIPTION }}
          CTMS_TR_CONTENT_TYPE: ${{ vars.CTMS_TR_CONTENT_TYPE }}
          CTMS_TR_STORAGE_TYPE: ${{ vars.CTMS_TR_STORAGE_TYPE }}
          CTMS_TR_USER_NAME: ${{ vars.CTMS_TR_USER_NAME }}
